# Generated by Django 3.1.3 on 2020-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201105_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
