# Generated by Django 3.1.3 on 2020-11-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='user',
            new_name='student',
        ),
    ]
