# Generated by Django 3.1.3 on 2020-11-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201105_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_time',
        ),
    ]
