# Generated by Django 3.1.3 on 2020-11-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20201105_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='week_day',
            field=models.CharField(default='Monday', max_length=100),
        ),
    ]
