# Generated by Django 3.1.3 on 2020-11-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20201105_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='week_day',
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='monday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
