# Generated by Django 3.1.3 on 2020-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20201106_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='friday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='friday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thrusday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tuesday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot1_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot1_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot1_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot2_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot2_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot2_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot3_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot3_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='wednesday_slot3_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
