# Generated by Django 3.1.3 on 2020-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20201107_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_copy',
            name='tot_lecture_count',
            field=models.IntegerField(default=0),
        ),
    ]
