# Generated by Django 3.1.3 on 2020-11-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_lecture_copy_tot_lecture_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='proxies_marked',
            field=models.IntegerField(default=0),
        ),
    ]
